import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";

import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { SkipLink } from "@/components/layout/skip-link";
import { site } from "@/content/site";
import { metadataBase } from "@/lib/seo";

import "./globals.css";

/* next/font owns these variable names; globals.css maps them onto the
   --font-sans / --font-mono theme tokens. They must NOT share a name with the
   theme token — a custom property that references itself resolves to nothing. */
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ["latin"],
  display: "swap",
});

/**
 * Site-wide metadata defaults. Spec: build-plan.md PORT-050.
 *
 * `metadataBase` CLOSES A BUG CARRIED SINCE PORT-030. Without it Next resolves
 * every relative metadata URL — including the `og:image` generated by
 * `opengraph-image.tsx` — against `http://localhost:3000`, and it does not fail
 * the build to tell you: it prints a warning and ships. A link shared from
 * production then advertises a card hosted on a machine nobody else can reach.
 *
 * The role line is now read from `site.role` rather than the hardcoded
 * "— Developer" this file carried for seven tickets, which had already drifted
 * from content: `site.role` says "Full-stack web developer".
 */
export const metadata: Metadata = {
  metadataBase,
  title: {
    /**
     * `default` is what a route with no title of its own gets; `template`
     * appends the site name to every page that sets one.
     *
     * This is why `buildPageMetadata` takes a BARE title — "Projects", not
     * "Projects — Vernel Aquino". A page passing the full string would render
     * "Projects — Vernel Aquino — Vernel Aquino", and it would look right in
     * the file that produced it.
     */
    default: `${site.name} — ${site.role}`,
    template: `%s — ${site.name}`,
  },
  description: site.tagline,
  applicationName: site.name,
  authors: [{ name: site.name, url: site.url }],
  creator: site.name,
  /**
   * Site-wide OG and Twitter defaults. A page's own values override these;
   * anything a page omits falls back here, so no page has to restate the
   * siteName or the locale.
   *
   * Deliberately no `images` key anywhere in this file: `app/opengraph-image.tsx`
   * is discovered by convention and Next injects the tags itself. Naming an
   * image here would override that discovery and blank the card.
   */
  openGraph: {
    type: "website",
    locale: "en_US",
    siteName: site.name,
    title: `${site.name} — ${site.role}`,
    description: site.tagline,
    url: site.url,
  },
  twitter: {
    card: "summary_large_image",
    title: `${site.name} — ${site.role}`,
    description: site.tagline,
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} ${jetbrainsMono.variable} h-full`}
    >
      <body className="flex min-h-full flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SkipLink />
          <Header />
          <main id="main" tabIndex={-1} className="scroll-mt-16 focus:outline-none">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
